checks:
    python:
        code_rating: true
        duplicate_code: true
    javascript: true
tools:
    pylint:
        python_version: '2'
        config_file: .pylintrc
filter:
    excluded_paths:
        - '*/tests/*'
build:
    cache:
        directories:
            - ./lib/python3.5/site-packages
            - ~/.analysis
    environment:
        python: '3.5.0'
        node: 'v6.2.0'
        variables:
            DJANGO_SETTINGS_MODULES: settings
        postgresql: true
        redis: true
    dependencies:
        override:
            - 'pip install -r requirements/test.txt'
    tests:
        before:
            - 'pip install coverage --force-reinstall -U'
        override:
            - pylint-run strat -j8
            -
                command: python -m pytest --cov=psqlextra
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
