site_name: django-postgres-extra
theme:
  name: 'rtd-dropdown'
pages:
- Home: index.md
- Manager: manager.md
- HStore: hstore.md
- Signals: signals.md
- Indexes: indexes.md
- Database engine: db-engine.md
