site_name: django-postgres-extra
theme: readthedocs
pages:
- Home: index.md
- Managers & Models: managers-models.md
- Conflict Handling: conflict-handling.md
- HStore: hstore.md
- Table Partitioning: table-partitioning.md
- Indexes: indexes.md
- Deletion: deletion.md
- Database engine: db-engine.md
- Major Releases: major-releases.md
extra_css: [extra.css]
plugins:
    - redirects:
        redirect_maps:
            'manager.md': 'managers-models.md'
            'conflict_handling.md': 'conflict-handling.md'
